// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using POSBill.EntityFramework;

#nullable disable

namespace POSBill.EntityFramework.Migrations
{
    [DbContext(typeof(RestaurantRetailPOSBillDBContext))]
    [Migration("20230325110120_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("POSBill.Domain.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("date_format")
                        .HasColumnType("int");

                    b.Property<int>("date_sep")
                        .HasColumnType("int");

                    b.Property<int>("dec_sep")
                        .HasColumnType("int");

                    b.Property<int>("def_print_destination")
                        .HasColumnType("int");

                    b.Property<int>("def_print_orientation")
                        .HasColumnType("int");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("graphic_links")
                        .HasColumnType("int");

                    b.Property<int>("inactive")
                        .HasColumnType("int");

                    b.Property<string>("language")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("last_visit_date")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("page_size")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("percent_dec")
                        .HasColumnType("int");

                    b.Property<string>("phone")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("pos")
                        .HasColumnType("int");

                    b.Property<int>("prices_dec")
                        .HasColumnType("int");

                    b.Property<int>("print_profile")
                        .HasColumnType("int");

                    b.Property<int>("qty_dec")
                        .HasColumnType("int");

                    b.Property<int>("query_size")
                        .HasColumnType("int");

                    b.Property<int>("rates_dec")
                        .HasColumnType("int");

                    b.Property<string>("real_name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("rep_popup")
                        .HasColumnType("int");

                    b.Property<int>("role_id")
                        .HasColumnType("int");

                    b.Property<int>("save_report_selections")
                        .HasColumnType("int");

                    b.Property<int>("show_codes")
                        .HasColumnType("int");

                    b.Property<int>("show_gl")
                        .HasColumnType("int");

                    b.Property<int>("show_hints")
                        .HasColumnType("int");

                    b.Property<string>("startup_tab")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("sticky_doc_date")
                        .HasColumnType("int");

                    b.Property<string>("theme")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("tho_sep")
                        .HasColumnType("int");

                    b.Property<int>("transaction_days")
                        .HasColumnType("int");

                    b.Property<int>("use_date_picker")
                        .HasColumnType("int");

                    b.Property<string>("user_id")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("POSBill.Domain.Models.security_roles", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("areas")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("inactive")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("role")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("sections")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("security_roles");
                });

            modelBuilder.Entity("POSBill.Domain.Models.stock_master", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("adjustment_account")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("category_id")
                        .HasColumnType("int");

                    b.Property<string>("cogs_account")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateOnly>("depreciation_date")
                        .HasColumnType("date");

                    b.Property<double>("depreciation_factor")
                        .HasColumnType("double");

                    b.Property<string>("depreciation_method")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<double>("depreciation_rate")
                        .HasColumnType("double");

                    b.Property<DateOnly>("depreciation_start")
                        .HasColumnType("date");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("dimension2_id")
                        .HasColumnType("int");

                    b.Property<int>("dimension_id")
                        .HasColumnType("int");

                    b.Property<int>("editable")
                        .HasColumnType("int");

                    b.Property<DateOnly>("fa_class_id")
                        .HasColumnType("date");

                    b.Property<int>("inactive")
                        .HasColumnType("int");

                    b.Property<string>("inventory_account")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<double>("labour_cost")
                        .HasColumnType("double");

                    b.Property<int>("long_description")
                        .HasColumnType("int");

                    b.Property<double>("material_cost")
                        .HasColumnType("double");

                    b.Property<string>("mb_flag")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("no_purchase")
                        .HasColumnType("int");

                    b.Property<int>("no_sale")
                        .HasColumnType("int");

                    b.Property<double>("overhead_cost")
                        .HasColumnType("double");

                    b.Property<double>("purchase_cost")
                        .HasColumnType("double");

                    b.Property<string>("sales_account")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("stock_id")
                        .HasColumnType("int");

                    b.Property<int>("tax_type_id")
                        .HasColumnType("int");

                    b.Property<string>("units")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("wip_account")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("stock_master");
                });
#pragma warning restore 612, 618
        }
    }
}
